---
# tasks file for httpd_setup
- name: Install Httpd
  yum:
    name: "{{ httpd_package_name }}"
    state: present
  become: true

- name: place custome HTML file
  copy:
    src: index.html
    dest: /var/www/html/index.html
  become: true

- name: start the service
  service:
    name: "{{ httpd_package_name }}"
    state: started
    enabled: yes
  become: true
